const SVG_TYPE = {
    HOME: 'HOME',
  SKILLS: 'SKILLS',
  PROJECT: 'PROJECT',
  CONTACT: 'CONTACT',
  REACT: 'REACT',
  SASS: 'SASS',
  STYLED_COMPONENTS: 'STYLED COMPONENTS',
  REDUX: 'REDUX',
  GIT: 'GIT',
  TYPESCRIPT: 'TYPESCRIPT',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN',
  MAIL: 'MAIL',
  SWIPE_UP: 'SWIPE_UP',
  };
  
  export default SVG_TYPE;
  
  